version: 2

sources:
  - name: main
    tables:
      - name: anime_bronze
        meta:
          dagster:
            asset_key: ["anime_bronze"]
      - name: character_bronze
        meta:
          dagster:
            asset_key: ["character_bronze"]
      - name: staff_bronze
        meta:
          dagster:
            asset_key: ["staff_bronze"]
      - name: studio_bronze
        meta:
          dagster:
            asset_key: ["studio_bronze"]
      - name: rss_chruncyroll_raw
        meta:
          dagster:
            asset_key: ["load_chruncyroll"]
      - name: rss_animenewsnetwork_raw
        meta:
          dagster:
            asset_key: ["load_animenewsnetwork"]
      - name: rss_otakukart_raw
        meta:
          dagster:
            asset_key: ["load_otakukart"]
